### ISSUE TITLE
GitBook?

### ISSUE THREAD

**Issue by justinclift** [NSIS-Dev/Documentation#5]
As a curiosity thought, have you looked at [GitBook](https://github.com/GitbookIO/gitbook)?

That works with Markdown, but has good online search capability.  Kind of thinking the search functionality would probably really help for NSIS reference material. 😁 

eg trying out the search functionality (in the top left) of the Django Girls Tutorial:

&nbsp; &nbsp; http://tutorial.djangogirls.org/en/index.html

Results are returned sub-second, which seems pretty nice.

**Comment by idleberg** [comment]
Thanks for the suggestion, but this repository is meant as a barebone Markdown source that can (and should) be utilized in many ways. It is currently used to create a [docset](https://github.com/idleberg/NSIS.docset) for Zeal or Dash, and serves as the basis of the upcoming new website. I was thinking about a PDF/Ebook option as well.

If you like GitBook, feel free to use the files in this repository under the terms of the license.

**Comment by justinclift** [comment]
No worries at all. :smile:
