### ISSUE TITLE
WinVer typos and syntax errors

### ISSUE THREAD

**Issue by tresf** [NSIS-Dev/Documentation#6]
According to NSIS on Ubuntu 14.04, `${If}` should generally take 4 parameters however, the documentation for most all `WinVer` examples show otherwise.

**Edit:** I just re-read the documentation which says this:

> The alpha release of NSIS (3.0a2) supports Windows 8 and 8.1.

An additional `since 3.0a2` should be added to the documentation since many build environments are still on 2.x.

e.g. 

```diff
# EDIT:  IGNORE THIS IT'S WRONG SEE COMMENT ABOVE.
+ ${If} ${AtLeastWin8.1} == true
- ${If} ${AtLeastWin8.1}
```

**Edit:** This part is still valid problem.

Secondly, what [appears to have been a search-and-replace](https://github.com/NSIS-Dev/Documentation/commit/461b90d464118ace05d2d51b104acc32228f7a65#diff-fe52dac6ce69749aa50bec332bb7d89eR1) has broken the anchors to show the wrong syntax.  Being the largest text on the page, this may result in incorrect usage.

```diff
+ # ${AtLeastWin8.}
- # ${AtLeastWin8}.1
```

Keywords:

```
!insertmacro: macro "_If" requires 4 parameter(s), passed 2!
Error in script "/home/foo/bar/build/_CPack_Packages/win32/NSIS/project.nsi" on line 10-- aborting creation process
```

**Comment by tresf** [comment]
I just re-read the documentation which says this:

> The alpha release of NSIS (3.0a2) supports Windows 8 and 8.1.

Since I'm on 2.x, I had missed this.  The docs should include a "Since version `x.x`" note in them perhaps?

**Comment by tresf** [comment]
>  If you wish to detect Windows 8 and 8.1 rather than just ${AtLeastWin7} or similar with NSIS stable you can use this script or update your local WinVer.nsh with the missing defines and macros from NSIS 3

Has [this statement been tested](http://nsis.sourceforge.net/Get_Windows_version#Semi-Obsolete)?  I tried to cherry-pick the new `WinVer` to 2.x and it threw more syntax errors.

**Edit:** Is `LogicLib` required for the [wiki examples](http://nsis.sourceforge.net/Get_Windows_version) to work?  They are missing it from the examples.

**Comment by idleberg** [comment]
> Is LogicLib required for the wiki examples to work? They are missing it from the examples.

LogicLib gets included in [WinVer.nsh](https://github.com/kichik/nsis/blob/14db933bd76097911ee7414a1a64d07fff215cb6/Include/WinVer.nsh#L106)

**Comment by tresf** [comment]
Bump for bots.

**Comment by tresf** [comment]
Why is this closed?

**Comment by tresf** [comment]
Bumping to keep open

**Comment by tresf** [comment]
Please don't close

**Comment by idleberg** [comment]
I‘ve lost track of this issue. The typo has been fixed and the history added some months ago. Can we close this?

**Comment by tresf** [comment]
> Secondly, what [appears to have been a search-and-replace](https://github.com/NSIS-Dev/Documentation/commit/461b90d464118ace05d2d51b104acc32228f7a65#diff-fe52dac6ce69749aa50bec332bb7d89eR1) has broken the anchors to show the wrong syntax. Being the largest text on the page, this may result in incorrect usage.

I can't even find the markdown files any longer, so sure. :)

**Comment by tresf** [comment]
Also, please accept my apologies, this bug report was filed 5 years ago.  I realize now re-reading it the following:

1. It's confusing to read
2. I should have just submitted a PR

:)
